# Generated by Django 4.2.15 on 2024-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_comment_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default=0, upload_to='uploads/posts'),
        ),
    ]
