# Generated by Django 4.2.15 on 2024-09-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_firstname_profile_lastname_profile_motto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='motto',
            new_name='bio',
        ),
    ]
